### ISSUE TITLE
Controller doesn't run with no GCS

### ISSUE THREAD

**Issue by arthurrichards77** [StarlingUAS/example_python_controller#4]
Running the example worked and drone took off when published to /mission_start BUT kept saying "take off 0.0/4.5" and foxglove showed no traffic on /v/mavros/xxx topics.  Got state but nothing else: no position or battery, for example.

It did all take off when I fired up QGroundControl.  Guess is that the GCS "requests" MAVLINK messages at certain rates, and the controller alone doesn't make those requests.

**Comment by arthurrichards77** [comment]
Correction by "it did all take off" it had already taken off - but on starting QGC, I suddenly got message on all the ros topics and the drone executed the mission successfully

**Comment by mhl787156** [comment]
@arthurrichards77 you said that you figured out a reason for this and possibly a fix? Would you be able to share it here in a comment as I think I need to implement a similar fix in the simple_offboard controller for ardupilot (https://github.com/StarlingUAS/starling_simple_offboard/pull/6)

**Comment by arthurrichards77** [comment]
Hi @mhl787156 - I think the answer is this: https://ardupilot.org/dev/docs/mavlink-requesting-data.html  It should be possible to send the appropriate request straight in from a ROS node using the mavros/to topic.  

Options appear to be https://mavlink.io/en/messages/common.html#REQUEST_DATA_STREAM or https://mavlink.io/en/messages/common.html#MAV_CMD_SET_MESSAGE_INTERVAL

REQUEST_DATA_STREAM looks easier to use but is marked as deprecated, replaced by SET_MESSAGE_INTERVAL.  Take your pick...
